// Code generated by go-swagger; DO NOT EDIT.

package tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ildomm/zus/models"
)

// CreateHashOKCode is the HTTP code returned for type CreateHashOK
const CreateHashOKCode int = 200

/*CreateHashOK Successful operation

swagger:response createHashOK
*/
type CreateHashOK struct {

	/*
	  In: Body
	*/
	Payload *models.TokenResponse `json:"body,omitempty"`
}

// NewCreateHashOK creates CreateHashOK with default headers values
func NewCreateHashOK() *CreateHashOK {

	return &CreateHashOK{}
}

// WithPayload adds the payload to the create hash o k response
func (o *CreateHashOK) WithPayload(payload *models.TokenResponse) *CreateHashOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create hash o k response
func (o *CreateHashOK) SetPayload(payload *models.TokenResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateHashOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateHashDefault error

swagger:response createHashDefault
*/
type CreateHashDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewCreateHashDefault creates CreateHashDefault with default headers values
func NewCreateHashDefault(code int) *CreateHashDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateHashDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create hash default response
func (o *CreateHashDefault) WithStatusCode(code int) *CreateHashDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create hash default response
func (o *CreateHashDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create hash default response
func (o *CreateHashDefault) WithPayload(payload *models.GeneralError) *CreateHashDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create hash default response
func (o *CreateHashDefault) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateHashDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
