// Code generated by go-swagger; DO NOT EDIT.

package tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// CreateHashHandlerFunc turns a function with the right signature into a create hash handler
type CreateHashHandlerFunc func(CreateHashParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateHashHandlerFunc) Handle(params CreateHashParams) middleware.Responder {
	return fn(params)
}

// CreateHashHandler interface for that can handle valid create hash params
type CreateHashHandler interface {
	Handle(CreateHashParams) middleware.Responder
}

// NewCreateHash creates a new http.Handler for the create hash operation
func NewCreateHash(ctx *middleware.Context, handler CreateHashHandler) *CreateHash {
	return &CreateHash{Context: ctx, Handler: handler}
}

/*CreateHash swagger:route POST /hash tokens createHash

Creates new hash

*/
type CreateHash struct {
	Context *middleware.Context
	Handler CreateHashHandler
}

func (o *CreateHash) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateHashParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateHashBody create hash body
// swagger:model CreateHashBody
type CreateHashBody struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this create hash body
func (o *CreateHashBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateHashBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateHashBody) UnmarshalBinary(b []byte) error {
	var res CreateHashBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
