// Code generated by go-swagger; DO NOT EDIT.

package tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetHashesHandlerFunc turns a function with the right signature into a get hashes handler
type GetHashesHandlerFunc func(GetHashesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHashesHandlerFunc) Handle(params GetHashesParams) middleware.Responder {
	return fn(params)
}

// GetHashesHandler interface for that can handle valid get hashes params
type GetHashesHandler interface {
	Handle(GetHashesParams) middleware.Responder
}

// NewGetHashes creates a new http.Handler for the get hashes operation
func NewGetHashes(ctx *middleware.Context, handler GetHashesHandler) *GetHashes {
	return &GetHashes{Context: ctx, Handler: handler}
}

/*GetHashes swagger:route GET /hashes tokens getHashes

Get all hashes received

Get all hashes received

*/
type GetHashes struct {
	Context *middleware.Context
	Handler GetHashesHandler
}

func (o *GetHashes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHashesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
