// Code generated by go-swagger; DO NOT EDIT.

package tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ildomm/zus/models"
)

// GetHashesOKCode is the HTTP code returned for type GetHashesOK
const GetHashesOKCode int = 200

/*GetHashesOK Successful operation

swagger:response getHashesOK
*/
type GetHashesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.TokenInfo `json:"body,omitempty"`
}

// NewGetHashesOK creates GetHashesOK with default headers values
func NewGetHashesOK() *GetHashesOK {

	return &GetHashesOK{}
}

// WithPayload adds the payload to the get hashes o k response
func (o *GetHashesOK) WithPayload(payload []*models.TokenInfo) *GetHashesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hashes o k response
func (o *GetHashesOK) SetPayload(payload []*models.TokenInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHashesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.TokenInfo, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetHashesDefault error

swagger:response getHashesDefault
*/
type GetHashesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewGetHashesDefault creates GetHashesDefault with default headers values
func NewGetHashesDefault(code int) *GetHashesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetHashesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get hashes default response
func (o *GetHashesDefault) WithStatusCode(code int) *GetHashesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get hashes default response
func (o *GetHashesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get hashes default response
func (o *GetHashesDefault) WithPayload(payload *models.GeneralError) *GetHashesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hashes default response
func (o *GetHashesDefault) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHashesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
