// Code generated by go-swagger; DO NOT EDIT.

package tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetHashsHandlerFunc turns a function with the right signature into a get hashs handler
type GetHashsHandlerFunc func(GetHashsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHashsHandlerFunc) Handle(params GetHashsParams) middleware.Responder {
	return fn(params)
}

// GetHashsHandler interface for that can handle valid get hashs params
type GetHashsHandler interface {
	Handle(GetHashsParams) middleware.Responder
}

// NewGetHashs creates a new http.Handler for the get hashs operation
func NewGetHashs(ctx *middleware.Context, handler GetHashsHandler) *GetHashs {
	return &GetHashs{Context: ctx, Handler: handler}
}

/*GetHashs swagger:route GET /hashes tokens getHashs

Get all hashs received

Get all hashs received

*/
type GetHashs struct {
	Context *middleware.Context
	Handler GetHashsHandler
}

func (o *GetHashs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHashsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
