// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// OptionsAllowOKCode is the HTTP code returned for type OptionsAllowOK
const OptionsAllowOKCode int = 200

/*OptionsAllowOK Successful operation

swagger:response optionsAllowOK
*/
type OptionsAllowOK struct {
}

// NewOptionsAllowOK creates OptionsAllowOK with default headers values
func NewOptionsAllowOK() *OptionsAllowOK {

	return &OptionsAllowOK{}
}

// WriteResponse to the client
func (o *OptionsAllowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
