// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// OptionsAllowHandlerFunc turns a function with the right signature into a options allow handler
type OptionsAllowHandlerFunc func(OptionsAllowParams) middleware.Responder

// Handle executing the request and returning a response
func (fn OptionsAllowHandlerFunc) Handle(params OptionsAllowParams) middleware.Responder {
	return fn(params)
}

// OptionsAllowHandler interface for that can handle valid options allow params
type OptionsAllowHandler interface {
	Handle(OptionsAllowParams) middleware.Responder
}

// NewOptionsAllow creates a new http.Handler for the options allow operation
func NewOptionsAllow(ctx *middleware.Context, handler OptionsAllowHandler) *OptionsAllow {
	return &OptionsAllow{Context: ctx, Handler: handler}
}

/*OptionsAllow swagger:route OPTIONS /* optionsAllow

OptionsAllow options allow API

*/
type OptionsAllow struct {
	Context *middleware.Context
	Handler OptionsAllowHandler
}

func (o *OptionsAllow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewOptionsAllowParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
