// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Zus API
This is the API specification for Zus token project


    Schemes:
      http
    Host: api.zus.com
    BasePath: /v1
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
