package main

import (
	"github.com/ildomm/zus/config"
	db "github.com/ildomm/zus/database"
	"github.com/ildomm/zus/utils"
	"log"
	"os"

	loads "github.com/go-openapi/loads"
	"github.com/ildomm/zus/restapi"
	"github.com/ildomm/zus/restapi/operations"
	flags "github.com/jessevdk/go-flags"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {
	config.Setup()
	utils.SetupLogger("server.log")

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewZusAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Zus API"
	parser.LongDescription = "This is the API specification for Zus token project"

	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	// Overrite flags
	server.Host = config.App.Runtime.Host
	server.Port = config.App.Runtime.Port
	server.ConfigureAPI()
	db.Setup()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
